x86/fpu: dovetail: enable alternate scheduling
Signed-off-by: Philippe Gerum <rpm@xenomai.org>

x86/fpu: fix compile error without kernel_fpu_disabled()

In v5.18-evl-rebase, function kernel_fpu_disabled() has been removed in
commit 59f5ede3bc0f("x86/fpu: Prevent FPU state corruption"), so we will
get compile error when CONFIG_DOVETAIL is enabled:
arch/x86/kernel/fpu/core.c:931:6: error: implicit declaration of function ‘kernel_fpu_disabled’; did you mean ‘perf_pmu_disable’? [-Werror=implicit-function-declaration]
    if (kernel_fpu_disabled()) {
        ^~~~~~~~~~~~~~~~~~~
        perf_pmu_disable
cc1: all warnings being treated as errors
So, fix it.

Signed-off-by: Jamie Huang <jamienstar@163.com>